# -*- coding: utf-8 -*-
"""analiza_sprzedazy_np_pd_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O12iC2I8lTSy3PIxCUmOS1OxjPx1Y3Mt

# Start projektu: Numpy, Pandas
"""

import numpy as np
import pandas as pd

#tworzenie danych za pomocą numpy
np.random.seed(42)
num_rows = 1000

data = {
    "OrderID":np.arange(1,num_rows+1),
    "CustomerID":np.random.randint(1000,2000,size=num_rows),
    "Amount":np.round(np.random.normal(200,50,size=num_rows)),
    "Region":np.random.choice(["North","South","East","West"],size=num_rows),
    "Returned":np.random.choice([True,False],size=num_rows,p=[0.1,0.9])
}

#utworzenie DataFrame w Pandas
df = pd.DataFrame(data)
df.head(5)

print(f"rozmiar danych: {df.shape}")

"""# Prosta analiza danych"""

print(f'\nŚredni przychód: {df["Amount"].mean()}')
print(f'\nLiczba zwrotów: {df["Returned"].sum()}')

#grupowanie po regionie
regions_stats = df.groupby("Region")["Amount"].agg(["count","mean","sum"])
print(f"\nStatystyki wg regionu\n {regions_stats}")

#filtrowanie danych
high_value = df[df["Amount"]>300]
print(f"\nTransakcje powyżej 300 zł: {high_value.shape[0]}")

#Histogram matplotlib
import matplotlib.pyplot as plt
df["Amount"].hist(bins=30)
plt.title("Rozkład kwot zamówień")
plt.xlabel("Kwota")
plt.ylabel("Liczba")
plt.show()