# -*- coding: utf-8 -*-
"""dane_dask__.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOX7ly2Phl6dUDl0MhoVKOLufu7AZ_-a
"""

!pip install dask[complete]

import pandas as pd
import numpy as np

n = 5_000_000

df = pd.DataFrame({
    "id":np.arange(n),
    "value":np.random.normal(100,20,size=n),
    "category":np.random.choice(['A','B','C'],size=n)
})

#zapis do pliku
df.to_csv("big_data.csv",index=False)

#wczytanie danych z użyciem deskim
import dask.dataframe as dd

ddf = dd.read_csv("big_data.csv")

print(ddf.head(10))

#proste operacje
mean_val = ddf["value"].mean()
print(f"Średnia (leniwa): {mean_val}")

print(f"Średnia (obliczona): {mean_val.compute()}")

grouped = ddf.groupby("category")["value"].mean()
print(f"Średnia per kategoria(leniwa): {grouped}")
print(f"Średnia per kategoria(obliczona): {grouped.compute()}")

print(f"Liczba partycji: {ddf.npartitions}")
print(f"rozmiar danych (szacowany): {ddf.memory_usage(deep=True).compute()}")