# -*- coding: utf-8 -*-
"""pyspark_dane_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EO8XBH3oroSk7Qjuug05rsrrtMrOwjJ8
"""

!pip install pyspark

from pyspark.sql import SparkSession

#towrzenie lub pobranie sesji Spark
spark = SparkSession.builder \
    .appName("Analiza zamówień") \
    .getOrCreate()

from pyspark.sql.types import StructType,StructField,IntegerType,StringType,DoubleType

#tworzenie schematu
schema = StructType([
    StructField("order_id",IntegerType(),True),
    StructField("customer_id",IntegerType(),True),
    StructField("category",StringType(),True),
    StructField("amount",DoubleType(),True)
])

#przykładowe dane
data = [
    (1,101,"electronics",299.99),
    (2,102,"books",16.22),
    (3,101,"books",22.99),
    (4,103,"electronics",499.0),
    (5,104,"clothing",79.90),
    (6,102,"books",12.97)
]

df = spark.createDataFrame(data,schema)
df.show()

#filtorwanie zamówień powyzej 100 zł
df.filter(df["amount"]>100).show()

#średnia wartość zamówienia w każdej kategorii
avg_by_category = df.groupBy("category").avg("amount")
avg_by_category.show()

#konwesja do pandas
pdf = avg_by_category.toPandas()

import matplotlib.pyplot as plt

plt.bar(pdf["category"],pdf["avg(amount)"])
plt.title("Średnia wartość zamówienia wg kategorii")
plt.ylabel("kwota [PLN]")
plt.xlabel("Kategoria")
plt.show()

spark.stop()