# -*- coding: utf-8 -*-
"""seg_autoenkoder_kmeans.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15CAJih66l-odbj5WPbCyE-Lyc2av1TXw
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras import layers, models

# === PRZYKŁADOWE DANE (lub wczytaj swoje) ===
np.random.seed(42)
n = 500
data = {
    'Recency': np.random.randint(1, 365, size=n),
    'Frequency': np.random.poisson(10, size=n),
    'Monetary': np.random.exponential(scale=100, size=n)
}
rfm = pd.DataFrame(data)

# === STANDARYZACJA ===
X = rfm[['Recency', 'Frequency', 'Monetary']].values
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# === BUDOWA AUTOENKODERA ===
input_dim = X_scaled.shape[1]
encoding_dim = 2

input_layer = layers.Input(shape=(input_dim,))
encoded = layers.Dense(10, activation='relu')(input_layer)
encoded = layers.Dense(encoding_dim, activation='relu')(encoded)

decoded = layers.Dense(10, activation='relu')(encoded)
decoded = layers.Dense(input_dim, activation='linear')(decoded)

autoencoder = models.Model(inputs=input_layer, outputs=decoded)
encoder = models.Model(inputs=input_layer, outputs=encoded)

autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.fit(X_scaled, X_scaled, epochs=100, batch_size=32, verbose=0)

# === ENKODOWANIE I KLASTERYZACJA ===
X_encoded = encoder.predict(X_scaled)
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
clusters = kmeans.fit_predict(X_encoded)

# === WIZUALIZACJA ===
rfm['Cluster'] = clusters
plt.figure(figsize=(8,6))
plt.scatter(X_encoded[:, 0], X_encoded[:, 1], c=clusters, cmap='viridis', s=20)
plt.title("Segmentacja klientów - Autoencoder + KMeans")
plt.xlabel("Encoded Dim 1")
plt.ylabel("Encoded Dim 2")
plt.grid(True)
plt.show()

# === ZAPIS DO CSV ===
rfm.to_csv("rfm_autoencoder_segments.csv", index=False)
print("Zapisano plik: rfm_autoencoder_segments.csv")